apiVersion: v1
data:
  mapUsers: |
    - userarn: arn:aws:iam::397834978306:user/github-action-user
      username: github-action-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapUsers":"- userarn: arn:aws:iam::397834978306:user/github-action-user\n  username: github-action-user\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2024-07-25T13:49:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2216"
  uid: d5d0c8df-5ca2-4862-a6b4-c21ef31c7a57
