name: Backend CI

on:
  workflow_call: # Allows this workflow to be called by other workflows

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust as needed

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint  # Replace with your lint command

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust as needed

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: CI=true npm test  # Simulates CI environment for tests