name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  lint:
    uses: ./.github/workflows/backend-ci.yml # Reuse CI workflow for lint job
    
  test:
    uses: ./.github/workflows/backend-ci.yml # Reuse CI workflow for test job

  build-and-push:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Tag Docker Image
        working-directory: ./starter/backend
        run: docker build -t 397834978306.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }} .
      - name: Push Docker Image
        run: docker push 397834978306.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }}
    env:
      DOCKER_USERNAME: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      DOCKER_PASSWORD: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Image Tag in Deployment Manifest
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.spec.template.spec.containers[0].image = strenv(IMAGE_URL)' deployment.yaml 
        env:
          IMAGE_URL:397834978306.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }}
      - name: Apply Deployment
        run: kubectl apply -f deployment.yaml
      - name: Rollout Restart
        run: kubectl rollout restart deployment aws-auth # Replace with your deployment name
